### ISSUE TITLE
Add prettyprinter* packages to LTS 4+

### ISSUE THREAD

**Issue by quchen** [fpco/lts-haskell#57]
The newly released prettyprinter* family of packages builds with all LTS releases >= 4, so nothing speaks against adding them to all that are still maintained. 

See https://github.com/fpco/stackage/pull/2548 for the general "add to Stackage" PR.

**Comment by cdornan** [comment]
@quchen I have added them to LTS 8. Because of the effort involved, we only occasionally add releases to the back-catalogue, and It is unlikely we will build anything older than 6 again, and 6 would be prioritised over 7, as LTS-6 is the final release for GHC 7.10.

Would you please raise separate issues for adding 'prettyprinter*' to lts-6 and/or lts-7.

**Comment by cdornan** [comment]
@quchen actually I have some LT labels now, so I am going to re-open the issue with the lts-6 label &mdash; add the lts-7 label too if you like.

**Comment by quchen** [comment]
Thanks! I don't *need* the package to be added to older LTSes, dont go out of your way for doing so. That said, I'd happily welcome you sneaking them in if it can piggy-back on some other change. :-)

**Comment by quchen** [comment]
I’m closing this so it doesn’t clutter up the issues. Prettyprinter is in LTS 8 and 9, which I’m assuming is what most people are using/migrating to anyway.
