### ISSUE TITLE
Why was gtksourceview3 dropped from LTS-9?

### ISSUE THREAD

**Issue by peti** [fpco/lts-haskell#72]
The package disappeared from lts-9.7. Meanwhile, other gtk packages were updated and the build of gtksourceview3 is now broken. I wonder why that choice was made?

**Comment by bergmark** [comment]
Due to issues with the build server/docker image https://github.com/fpco/lts-haskell/issues/71

**Comment by peti** [comment]
Is that kind of thing (dropping packages because they no longer compile after their dependencies were updated) common practice in a "long term support" package set?

**Comment by bergmark** [comment]
No I don't think we've had to do that before, but what makes you say it's because of dependency updates?

**Comment by peti** [comment]
I assume there is a connection, because gtk, gtk2hs-buildtools, and gtk3 all had a version bump at the same time as gtksourceview3 broke. Is that not the cause?

**Comment by bergmark** [comment]
Sorry for the late reply! It might be because of that, it's not obvious to me where that header file is supposed to be coming from. I can't build gtksourceview3 locally either so I filed https://github.com/gtk2hs/gtksourceview/issues/4. If we can get a fix released soon that should be the easiest way to get it back into LTS 9.

**Comment by DanBurton** [comment]
> Is that kind of thing (dropping packages because they no longer compile after their dependencies were updated) common practice in a "long term support" package set?

It is not our practice to do this. In such a case, we would constrain the dependencies (instead of update them) to use the version already known to work in the LTS package set.

However, it appears there was a different, exceptional circumstance with LTS 9 and gtksourceview3 that caused us to remove it.

**Comment by hamishmack** [comment]
I am in favour of removing `gtksourceview3` from LTS and adding `gi-gtksource` in its place.  gtk2hs packages are a pain to maintain and I am not sure if anyone uses gtksourceview3 (Leksah used to but now uses gi-gtksource).

While we are at it could we please add:
* binary-shared
* gi-gtk-hs
* gi-gtksource
* gi-gtkosxapplication (might be tricky because it only builds on macOS)
* gi-webkit2

**Comment by mgsloan** [comment]
Another thing to note here: I'm not sure what the meaning of these flags are, but based on leksah's stack.yaml, it seems that the snapshot should also have some flags for these gi-* packages: https://github.com/leksah/leksah/blob/master/stack.yaml#L33

**Comment by juhp** [comment]
@hamishmack gi-webkit2 will require dropping gi-webkit: current leksah releases still need it I think.

**Comment by juhp** [comment]
gi-gtkosxapplication might require a PR.

**Comment by juhp** [comment]
binary-shared, gi-gtk-hs, and gi-gtksource should be in LTS 9.19.

**Comment by hamishmack** [comment]
@juhp Leksah only depends on `gi-webkit` if the `webkit2` cabal flag is disabled.  When the flag is enabled (which it is by default) Leksah uses `gi-webkit2` instead.

**Comment by juhp** [comment]
Alright I see, so far I have added gi-webkit2 for Nightly (it didn't have gi-webkit).

**Comment by juhp** [comment]
If noone has any objections then let's make these changes to LTS 9.20:
- remove gi-webkit
- add gi-webkit2
- bump gi-javascriptcore from version 3 to 4
- bump JavaScriptCore-3 to JavaScriptCore-4 in the docker image
