### ISSUE TITLE
Add wrecker-ui to LTS 9

### ISSUE THREAD

**Issue by bergmark** [fpco/lts-haskell#76]
https://github.com/fpco/stackage/pull/2858#issuecomment-345735981

**Comment by DanBurton** [comment]
I can't quite figure out how to wrangle the constraints to allow for `wrecker-ui` in LTS 9. The problem is its dependency, `distributed-process-simplelocalnet`.

- the newest version (distributed-process-simplelocalnet-0.2.4) requires a version of `network-transport` that is too new (1 major bump ahead: need 0.5.* but got 0.4.*)
- the next-to-newest version (distributed-process-simplelocalnet-0.2.3.3) requires a version of `distributed-process`, which in turn, requires a version of `syb` which is too old (1 major bump behind, need <0.7 but got 0.7.*)

**Comment by juhp** [comment]
Package is not in Nightly either for the record

**Comment by snoyberg** [comment]
I just ran into this as well. Closing, it can be reopened if the dependency issue is resolved.
